package org.example.hadoop.Aggregate2;

public enum ProcessingCounters {
  METADATA_RECORDS_PROCESSED,
  MEASUREMENT_RECORDS_PROCESSED,
  HEADER_RECORDS_PROCESSED,
  SKIPPED_RECORDS,
  EMPTY_VALUES_FOUND,
  STATION_ID_MATCHES_FOUND,
  STATION_ID_MISMATCHES_FOUND
}